### ISSUE TITLE
Thanks !!

### ISSUE THREAD

**Issue by chhetripradeep** [noirbizarre/gonja#1]
Thank you for writing this library. I took me sometime to find this library. I am playing around with it.

**Comment by noirbizarre** [comment]
Hi !
Glad it useful to someone. Maybe I need to advertise it a little bit so it's more discoverable.
Don't hesistate to dosome feedback.

**Comment by breml** [comment]
Same here, it took me a while to find this library, but it does what I am looking for.
In regards to advertisement, a good starting point would be to update the README.md to better highlight the functionalities. In particular, I have been looking for a package, that allows for the Jinja2 filter syntax (e.g. `{{ foo | default("bar") }}`). On first sight, when I was reading the examples in the README, I thought this library will not do the trick. Only when I dug deeper and had a look at the code, I figured out, that in fact this library does support the Jinja2 filter format.

Thanks and I hope you are still maintaining this library.
